var SETTING_FIND_WINS = true;
var SETTING_ROW_NUMBERS = true;
var SETTING_ROW_NOTATION = false;
var SETTING_ROT_ANIM = true;
var SETTING_ROT_SPEED = 3;
var SETTING_AI_PLACE_DELAY = 300;
var SETTING_AI_ROTATE_DELAY = 1000;
var SETTING_PLAYER_WORKER = true;