//Sizes
var UNIT_SIZE = 30;
var HALF_UNIT = UNIT_SIZE / 2;
var QUAD_SIZE = UNIT_SIZE * 3;
var BOARD_SIZE = UNIT_SIZE * 6;
var HALF_BOARD = BOARD_SIZE / 2;
var ARROW_TARGET_SIZE = BOARD_SIZE + (3 * UNIT_SIZE);
var HALF_ARROW_TARGET = ARROW_TARGET_SIZE / 2;

//Settings
var SETTING_ROT_ANIM = true;


var ROTATION_DURATION = 500;